### ISSUE TITLE
Should structs be allowed to have duplicate field names?

### ISSUE THREAD

**Issue by dkrautha** [XtensibleBinaryFormat/XBF#54]
My assumption here is no, however it is not explicitly defined that way in the specification. We need to define how collisions should be handled, if at all, as it will determine how #53 gets implemented.

**Comment by dkrautha** [comment]
It's been decided that structs can't have duplicate field names for hopefully obvious reasons. This needs to be formalized in the specification.

Beyond this formalization, a decision needs to be made on how the Rust implementation is going to handle what happens when a user tries to incorrectly create struct metadata. The current working implementation in #55 assumes that this is an error, and as such there are checked and unchecked constructors for the type. 

The API and implementation could be simplified however if this behavior was instead handled as a typical HashMap would, and the previous entry is overwritten with the new one. I think there are a number of problems with this silent failure, and unless somebody reads the documentation that specifies this behavior, they wouldn't know it could occur. Despite this, its likely that this would be a more performant solution, so I'm looking for feedback on this.

**Comment by ahuston-0** [comment]
I''m of the opinion that it should be a loud failure, and if someone were ever to want a setting that allowed them to silently replace an item with the same key then that should be a feature flag or something. The big area where I could see something like that being useful is merging two structs or vectors on the receiving end (ie. say i want to do set operations on two XBF vecs received in separate transactions or over a delta API). This then asks questions that should be answered by #56 though.

**Comment by ahuston-0** [comment]
> Beyond this formalization, a decision needs to be made on how the Rust implementation is going to handle what happens when a user tries to _incorrectly create struct metadata_.

Can you please clarify what is meant by incorrectly here? Is that a reference to the duplicate key issue?

**Comment by dkrautha** [comment]
Yup its the duplicate key issue, you'd have incorrectly created metadata if you had duplicate field names / keys

**Comment by ahuston-0** [comment]
Yeah okay thats what i thought based on the PR but just wanted to check.
